export const logoWebsites = {
  "Logo-1.png": "https://www.google.com",
  "Logo-2.png": "https://www.microsoft.com",
  "Logo-3.png": "https://www.apple.com",
  "Logo-4.png": "https://www.amazon.com",
  "Logo-5.png": "https://www.facebook.com",
  "Logo-6.png": "https://www.twitter.com",
  "Logo-7.png": "https://www.linkedin.com",
  "Logo-8.png": "https://www.instagram.com",
  "Logo-9.png": "https://www.youtube.com",
  "Logo-10.png": "https://www.netflix.com",
  "Logo-12.png": "https://www.adobe.com",
  "Logo-13.png": "https://www.salesforce.com",
  "Logo-14.png": "https://www.oracle.com",
  "Logo-15.png": "https://www.ibm.com",
  "Logo-16.png": "https://www.intel.com",
  "Logo-17.png": "https://www.nvidia.com",
  "Logo-18.png": "https://www.tesla.com",
  "Logo-19.png": "https://www.uber.com",
  "Logo-20.png": "https://www.airbnb.com",
  "Logo-21.png": "https://www.spotify.com",
  "Logo-22.png": "https://www.zoom.us",
  "Logo-23.png": "https://www.slack.com",
  "Logo-24.png": "https://www.dropbox.com",
  "Logo-25.png": "https://www.github.com",
  "Logo-26.png": "https://www.gitlab.com",
  "Logo-27.png": "https://www.atlassian.com"
};